export const STOPWORDS = new Set(["for", "and", "the", "a", "of", "with", "to"]);

export const PREFIXES = ["get", "try", "use", "go", "my", "join", "hey"];

export const SUFFIXES = [
  "ly",
  "ify",
  "hq",
  "hub",
  "labs",
  "kit",
  "spot",
  "zone",
  "now",
  "app",
];

// Small curated synonym map for common business/product words. Intentionally
// static (no LLM) — kept short and hand-picked rather than exhaustive.
export const SYNONYMS: Record<string, string[]> = {
  shop: ["store", "market", "mart"],
  store: ["shop", "market", "mart"],
  market: ["shop", "store", "bazaar"],
  fast: ["quick", "rapid", "swift"],
  quick: ["fast", "rapid", "swift"],
  home: ["house", "nest", "dwell"],
  house: ["home", "nest", "dwell"],
  food: ["eats", "meal", "dish"],
  dog: ["pup", "canine", "hound"],
  cat: ["feline", "kitty"],
  pet: ["animal", "critter"],
  clean: ["tidy", "fresh", "pure"],
  fresh: ["clean", "new", "crisp"],
  smart: ["clever", "bright", "sharp"],
  easy: ["simple", "smooth"],
  simple: ["easy", "plain"],
  green: ["eco", "organic"],
  eco: ["green", "organic"],
  organic: ["natural", "green", "eco"],
  natural: ["organic", "pure"],
  travel: ["trip", "journey", "voyage"],
  trip: ["travel", "journey"],
  learn: ["study", "teach", "school"],
  study: ["learn", "school"],
  teach: ["learn", "coach", "tutor"],
  build: ["make", "craft", "forge"],
  make: ["build", "craft", "create"],
  create: ["make", "build", "craft"],
  work: ["job", "task", "labor"],
  job: ["work", "gig", "task"],
  money: ["cash", "funds", "wealth"],
  cash: ["money", "funds"],
  finance: ["money", "wealth", "capital"],
  health: ["wellness", "care", "fit"],
  fit: ["health", "active"],
  wellness: ["health", "care"],
  care: ["health", "support"],
  kids: ["children", "youth"],
  children: ["kids", "youth"],
  book: ["read", "novel", "story"],
  read: ["book", "study"],
  music: ["sound", "audio", "tunes"],
  sound: ["audio", "music"],
  photo: ["picture", "image", "shot"],
  picture: ["photo", "image"],
  video: ["clip", "film", "movie"],
  film: ["video", "movie"],
  design: ["create", "craft", "style"],
  style: ["design", "fashion"],
  fashion: ["style", "wear"],
  wear: ["fashion", "apparel"],
  coffee: ["brew", "cafe", "espresso"],
  cafe: ["coffee", "bistro"],
  tea: ["brew", "chai"],
  car: ["auto", "vehicle", "ride"],
  auto: ["car", "vehicle"],
  bike: ["cycle", "ride"],
  cycle: ["bike", "ride"],
  game: ["play", "arcade"],
  play: ["game", "fun"],
  fun: ["play", "joy"],
  event: ["gathering", "meetup"],
  party: ["celebration", "bash"],
  wedding: ["ceremony", "nuptials"],
  gift: ["present", "surprise"],
  present: ["gift"],
  art: ["craft", "creative"],
  craft: ["art", "make", "build"],
  law: ["legal", "counsel"],
  legal: ["law"],
  tax: ["finance"],
  data: ["info", "insight", "analytics"],
  info: ["data", "insight"],
  cloud: ["hosting", "server"],
  code: ["dev", "software"],
  dev: ["code", "build"],
  software: ["app", "program", "code"],
  app: ["software", "tool"],
  tool: ["app", "utility"],
  agency: ["studio", "firm"],
  studio: ["agency", "workshop"],
  firm: ["agency", "company"],
  company: ["firm", "business"],
  business: ["company", "venture"],
  startup: ["venture", "business"],
  venture: ["startup", "business"],
};
